apiVersion: v1
kind: Service
metadata:
  name: nestapi
  labels:
    app: nestapi
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: api
    - port: 9000
      targetPort: 80
      name: angular
  selector:
    app: nestapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestapi
  labels:
    app: nestapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestapi
  template:
    metadata:
      labels:
        app: nestapi
    spec:
      containers:
        - name: nestapi
          image: docker.io/library/nest-api
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "20"
          imagePullPolicy: IfNotPresent
        - name: angularspa
          image: localhost/angular-spa
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
